fruits = []
a = input("Enter the fruit name: ")
fruits.append(a)
b = input("Enter the fruit name: ")
fruits.append(b)
c = input("Enter the fruit name: ")
fruits.append(c)
d = input("Enter the fruit name: ")
fruits.append(d)
e = input("Enter the fruit name: ")
fruits.append(e)
f = input("Enter the fruit name: ")
fruits.append(f)
g = input("Enter the fruit name: ")
fruits.append(g)
print(fruits)