marks = []
a = int(input("Enter the marks person1: "))
marks.append(a)
b = int(input("Enter the marks person2: "))
marks.append(b)
c = int(input("Enter the marks person3: "))
marks.append(c)
d = int(input("Enter the marks person4: ")) 
marks.append(d)
e = int(input("Enter the marks person5: "))
marks.append(e)
f = int(input("Enter the marks person6: "))
marks.append(f)
g = int(input("Enter the marks person7: "))
marks.append(g)
marks.sort()
print(marks)